name: Go

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  go:
    uses: openconfig/common-ci/.github/workflows/basic_go.yml@41d1f089c99a3096d3d2ed79598d8597310e12ea
    with:
      static-analysis-excludes-regex: exampleoc
      skip-gofmt: true
      skip-staticcheck: true

  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.x'

    - name: Generate and Check Diff
      # Ignore whitespace because goimports seems to modifying the generated commands inconsistently.
      run: |
        go generate ./...
        git diff --exit-code --ignore-all-space --ignore-blank-lines 
