name: Go

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  Go:
    uses: openconfig/common-ci/.github/workflows/basic_go.yaml@975b88475ea1efbd8d602a5e2082c8b2509b95c3
    with:
      static-analysis-excludes-regex: exampleoc
      skip-gofmt: true

  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.x'

    - name: Generate and Check Diff
      # Ignore whitespace because goimports seems to modifying the generated commands inconsistently.
      run: |
        go generate ./...
        git diff --exit-code --ignore-all-space --ignore-blank-lines 
