name: Go

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  go:
    uses: openconfig/common-ci/.github/workflows/go.yml@a0a686b0792f164c0cf587825fd742223abe9dc1
    with:
      static-analysis-excludes-regex: exampleoc
      skip-gofmt: true
      skip-staticcheck: true

  linter:
    uses: openconfig/common-ci/.github/workflows/linter.yml@a0a686b0792f164c0cf587825fd742223abe9dc1

  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.x'

    - name: Generate and Check Diff
      # Ignore whitespace because goimports seems to modifying the generated commands inconsistently.
      run: |
        go generate ./...
        git diff --exit-code --ignore-all-space --ignore-blank-lines 
